
steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
      cd environments/$BRANCH_NAME
      ls
      echo "*************** DONE ******************"

# [END tf-apply]      
