
steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
      

- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd environments/$BRANCH_NAME/terraform
      ls
      terraform init -reconfigure
      echo "**********INIT DONE***********"

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd environments/$BRANCH_NAME/terraform
      terraform plan 
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd environments/$BRANCH_NAME/terraform
      echo "**********ASK for approval!!!***********"      
      terraform apply -auto-approve
# [END tf-apply] 

# [START tf-destroy]
 - id: 'tf destroy'
   name: 'hashicorp/terraform:1.0.0'
   entrypoint: 'sh'
   args: 
   - '-c'
   - | 
       cd environments/$BRANCH_NAME/terraform      
       terraform destroy -auto-approve
       echo "**********Finish destroy 2***********"  
# [END tf-destroy]      